### ISSUE TITLE
@Transactional anottation not necessary

### ISSUE THREAD

**Issue by PanosCS** [bozduran/PostSite#1]
If you only use the inherited methods of CrudRepository in your AccountRepository and do not define any custom database operations, then you do not need to use the Transactional ann.

This is because the inherited methods of CrudRepository are already annotated with Transactional by default, which means that they will be executed within a transaction context. Therefore, if you only use these methods in your service layer, you do not need to specify the Transactional annotation explicitly.

https://github.com/bozduran/PostSite/blob/a216178408d32dec65c461556f3cec10e12e5b3c/src/main/java/com/bozduran/site/service/AccountService.java#L15-L23

**Comment by bozduran** [comment]
Done
